### PR TITLE
Simplify loading from prefixmaps

### PR DESCRIPTION
**Pull request by cthoyt**

### CODE REVIEW

**Comment by cthoyt** [comment]
@hrshdhgd this is a very small change, can you please enable CI and if there are no issues, merge? thanks!

**Comment by cthoyt** [comment]
hmm, looks like we'll need to update prefixmaps

**Comment by cthoyt** [comment]
@hrshdhgd updating prefixmaps solves the problem. Can you approve running this on CI?

**Review by cmungall — APPROVED** [review]

**Comment by cthoyt** [comment]
Thanks @cmungall. It would be great to get a release on this so we can update several other PRs waiting on this

**Comment by cthoyt** [comment]
cheers @hrshdhgd , much appreciated

**Pull request merged**
